### ISSUE TITLE
There is problem about lambda function permission when executing sagemaker pipeline.

### ISSUE THREAD

**Issue by heungh** [aws-solutions-library-samples/guidance-for-ai-driven-player-insights-on-aws#1]
There is ommited IAM policy
So when I executed sagemaker pipeline , I got error like below:

`User: arn:aws:sts::111111111111:assumed-role/PlayerChurn-Stack-EndpointEndpointFunctionServiceR-olm9xxxxxxxx/PlayerChurn-Stack-EndpointEndpointFunctionxxxxxx-xxxxxxxxxxxx is not authorized to perform: sagemaker:CreateEndpoint on resource: arn:aws:sagemaker:us-east-1:11111111111111:endpoint-config/PlayerChurnxxxxx because no identity-based policy allows the sagemaker:CreateEndpoint action`

I checked IAM Role of lambda function such as PlayerChurn2-Stack-EndpointEndpointFunction2...
and there is no assumed policy of sagemaker for trusted relationship tab.
So I fixed it like below.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": [
                    "lambda.amazonaws.com",
                    "sagemaker.amazonaws.com"
                ]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

After modifying it, I saw the pipelines executions got all successes.

**Comment by trenton-p** [comment]
Resolved "EndpointPermissions" Policy to address non-lower case endpoint config resources.

**Comment by trenton-p** [comment]
See commit #88177b2
